update .zshrc to be more portable

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -1,59 +1,91 @@
-# If you come from bash you might have to change your $PATH.
-# one place to set up PATH
-export PATH="${HOME}/bin:${HOME}/.local/bin:${PATH}"
+# Base PATH setup
+export PATH="$HOME/bin:$HOME/.local/bin:$PATH"
+
 if [[ "$(uname)" == "Darwin" ]]; then
   export PATH="/opt/homebrew/bin:/opt/homebrew/opt/ruby/bin:$PATH"
 elif [[ "$(uname)" == "Linux" ]]; then
   # ToDo
+  :
 fi
 
+# PNPM
+export PNPM_HOME="$HOME/Library/pnpm"
+[[ ":$PATH:" != *":$PNPM_HOME:"* ]] && export PATH="$PNPM_HOME:$PATH"
 
-# Path to your oh-my-zsh installation.
+# libpq (e.g. Postgres)
+export PATH="$PATH:/opt/homebrew/opt/libpq/bin"
+
+# Pyenv
+export PYENV_ROOT="$HOME/.pyenv"
+if command -v pyenv >/dev/null; then
+  [[ ":$PATH:" != *":$PYENV_ROOT/bin:"* ]] && export PATH="$PYENV_ROOT/bin:$PATH"
+  eval "$(pyenv init -)"
+  eval "$(pyenv virtualenv-init -)"
+fi
+
+# Oh My Zsh setup
 export ZSH="$HOME/.oh-my-zsh"
+if [[ -f "$ZSH/oh-my-zsh.sh" ]]; then
+  COMPLETION_WAITING_DOTS="true"
 
-COMPLETION_WAITING_DOTS="true"
+  plugins=(
+    bazel
+    gcloud
+    git
+    terraform
+    you-should-use
+    z
+    zsh-autosuggestions
+    zsh-eza
+    zsh-syntax-highlighting
+  )
 
-plugins=(
-  bazel
-  fzf
-  gcloud
-  git
-  terraform
-  you-should-use
-  z
-  zsh-autosuggestions
-  zsh-eza
-  zsh-syntax-highlighting
-)
+  unalias llm
+  source "$ZSH/oh-my-zsh.sh"
+  fpath+=("${ZSH_CUSTOM:-${ZSH:-$HOME/.oh-my-zsh}/custom}/plugins/zsh-completions/src")
+else
+  echo "Warning: oh-my-zsh not found at $ZSH" >&2
+fi
 
-source $ZSH/oh-my-zsh.sh
+# Shell behavior
+set -o vi
+bindkey -M vicmd v edit-command-line
 
-# User configuration
-source $HOME/.zshenv
+# User config
+[[ -f "$HOME/.zshenv" ]] && source "$HOME/.zshenv"
 
-export oak="$HOME/src/nuts/oak" # convenience on the CLI
-export EDITOR=nvim
-
-# set up bat
-export MANPAGER="sh -c 'col -bx | bat -l man -p'"
-alias cat='bat'
-alias pcat='bat --plain'
-
+# Aliases and tools
+export oak="$HOME/src/nuts/oak"
 alias oak='cd "$oak"'
-alias vim='nvim'
-alias vi='nvim'
 
-alias cm='chezmoi'
-alias cme='chezmoi edit'
-alias cmez="chezmoi edit ${HOME}/.zshrc"
-alias cmcd='cd "$(chezmoi source-path)"'
+if command -v nvim >/dev/null; then
+  export EDITOR=nvim
+  alias vim='nvim'
+  alias vi='nvim'
+elif command -v vim >/dev/null; then
+  export EDITOR=vim
+  alias vi='vim'
+fi
+
+if command -v bat >/dev/null; then
+  export MANPAGER="sh -c 'col -bx | bat -l man -p'"
+  alias cat='bat'
+  alias pcat='bat --plain'
+fi
+
+if command -v chezmoi >/dev/null; then
+  alias cm='chezmoi'
+  alias cme='chezmoi edit'
+  alias cmez="chezmoi edit ${HOME}/.zshrc"
+  alias cmcd='cd "$(chezmoi source-path)"'
+fi
 
 alias ds="$oak/tools/localdev/docker_stop.sh"
 alias de="$oak/tools/localdev/docker_ensure.sh"
 
-alias '?'='bc -le' # quick & dirty calculator
+command -v bc >/dev/null && alias '?'='bc -le'
 
-# git aliases
+# Git aliases
 alias g=git
 alias ga='git add'
 alias gaa='git add --all'
@@ -84,11 +116,12 @@ alias glols='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgr
 alias glp=_git_log_prettily
 alias gp='git push'
 alias gpd='git push --dry-run'
-alias 'gpf!'='git push --force-with-leae'
+alias 'gpf!'='git push --force-with-lease'
 alias grb='git rebase'
 alias grba='git rebase --abort'
 alias grbc='git rebase --continue'
 alias grbi='git rebase --interactive'
+alias gs='git switch'
 alias gss='git status --short'
 alias gst='git status'
 alias gsta='git stash push'
@@ -102,71 +135,46 @@ alias gsts='git stash show --patch'
 alias gunwip='git rev-list --max-count=1 --format="%s" HEAD | grep -q "\--wip--" && git reset HEAD~1'
 alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit --no-verify --no-gpg-sign --message "--wip-- [skip ci]"'
 
-
-fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
-
-source "$HOME/.sdkman/bin/sdkman-init.sh"
-
-# API keys
-for f in $(ls $HOME/secrets/*.sh); do
-  source $f
-done
-
-# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
-[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
-
-set -o vi
-
-# PATH and completions for gcloud
-if [ -f '$HOME/apps/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/cfesler/apps/google-cloud-sdk/path.zsh.inc'; fi
-if [ -f '$HOME/apps/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/cfesler/apps/google-cloud-sdk/completion.zsh.inc'; fi
-
-#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
+# SDKMAN
 export SDKMAN_DIR="$HOME/.sdkman"
 [[ -s "${SDKMAN_DIR}/bin/sdkman-init.sh" ]] && source "${SDKMAN_DIR}/bin/sdkman-init.sh"
 
-# homebrew-installed postgres
-export PATH="${PATH}:/opt/homebrew/opt/libpq/bin"
+# GCloud
+[[ -f "$HOME/apps/google-cloud-sdk/path.zsh.inc" ]] && source "$HOME/apps/google-cloud-sdk/path.zsh.inc"
+[[ -f "$HOME/apps/google-cloud-sdk/completion.zsh.inc" ]] && source "$HOME/apps/google-cloud-sdk/completion.zsh.inc"
 
-# opam configuration
-[[ ! -r $HOME/.opam/opam-init/init.zsh ]] || source /Users/cfesler/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
-
-export PYENV_ROOT="$HOME/.pyenv"
-command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
-eval "$(pyenv init -)"
-eval "$(pyenv virtualenv-init -)"
+# opam
+[[ -r "$HOME/.opam/opam-init/init.zsh" ]] && source "$HOME/.opam/opam-init/init.zsh" >/dev/null 2>/dev/null
 
 # fnm
-eval "$(fnm env --use-on-cd)"
-# pnpm
-export PNPM_HOME="$HOME/Library/pnpm"
-case ":$PATH:" in
-  *":$PNPM_HOME:"*) ;;
-  *) export PATH="$PNPM_HOME:$PATH" ;;
-esac
-# pnpm end
+command -v fnm >/dev/null && eval "$(fnm env --use-on-cd)"
 
-# Begin Shell-GPT integration ZSH v0.2
-_sgpt_zsh() {
-if [[ -n "$BUFFER" ]]; then
-    _sgpt_prev_cmd=$BUFFER
-    BUFFER+="⌛"
-    zle -I && zle redisplay
-    BUFFER=$(sgpt --shell <<< "$_sgpt_prev_cmd" --no-interaction)
-    zle end-of-line
-fi
-}
-zle -N _sgpt_zsh
-bindkey ^g _sgpt_zsh
-# End Shell-GPT integration ZSH v0.2
-
-# Check that the function `starship_zle-keymap-select()` is defined.
-# xref: https://github.com/starship/starship/issues/3418
-type starship_zle-keymap-select >/dev/null || \
-  {
-    eval "$(starship init zsh)"
+# Shell-GPT integration
+if command -v sgpt >/dev/null; then
+  _sgpt_zsh() {
+    if [[ -n "$BUFFER" ]]; then
+      _sgpt_prev_cmd=$BUFFER
+      BUFFER+="⌛"
+      zle -I && zle redisplay
+      BUFFER=$(sgpt --shell <<< "$_sgpt_prev_cmd" --no-interaction)
+      zle end-of-line
+    fi
   }
+  zle -N _sgpt_zsh
+  bindkey ^g _sgpt_zsh
+fi
 
+# starship
+if command -v starship >/dev/null; then
+  type starship_zle-keymap-select >/dev/null || eval "$(starship init zsh)"
+fi
 
-# Added by Windsurf
-export PATH="/Users/cfesler/.codeium/windsurf/bin:$PATH"
+# atuin
+command -v atuin >/dev/null && eval "$(atuin init zsh --disable-up-arrow)"
+
+# API keys
+if [[ -d "$HOME/secrets" ]]; then
+  for f in "$HOME"/secrets/*.sh; do
+    [[ -f $f ]] && source "$f"
+  done
+fi
